### ISSUE TITLE
error

### ISSUE THREAD

**Issue by scomnoob** [yousofs/telegram-media-downloader#1]
hello
win11
python 3.13

Enter download directory (or press Enter for default 'downloads'):
914.jpg:   0%|                                                           | 0.00/161k [00:00<?, ?B/s]
903.jpg:   0%|                                                           | 0.00/137k [00:00<?, ?B/s]
899.jpg:   0%|                                                           | 0.00/136k [00:00<?, ?B/s]
Traceback (most recent call last):
  File "C:\Users\strto\Downloads\telegram-media-downloader-master\telegram-media-downloader-master\main.py", line 289, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "C:\Users\strto\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\strto\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\strto\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\strto\Downloads\telegram-media-downloader-master\telegram-media-downloader-master\main.py", line 285, in main
    await main_menu()
  File "C:\Users\strto\Downloads\telegram-media-downloader-master\telegram-media-downloader-master\main.py", line 256, in main_menu
    await download_media_list(channel, selected_media, download_dir)
  File "C:\Users\strto\Downloads\telegram-media-downloader-master\telegram-media-downloader-master\main.py", line 150, in download_media_list
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strto\Downloads\telegram-media-downloader-master\telegram-media-downloader-master\main.py", line 102, in download_media
    path = os.path.join(download_dir, filename)
  File "<frozen ntpath>", line 139, in join
  File "<frozen genericpath>", line 188, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by yousofss** [comment]
Fixed in commit [656c50b426ec1effda629da49edd8267c1c5aec3].
Please try again and let me know if this resolves your issue!
